# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_atmosfera_estandar.ui'
#
# Created: Thu Jun 23 00:50:25 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(594, 235)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.titulo = QtGui.QLabel(Dialog)
        self.titulo.setMinimumSize(QtCore.QSize(0, 65))
        self.titulo.setObjectName("titulo")
        self.horizontalLayout_10.addWidget(self.titulo)
        self.units_groupBox = QtGui.QGroupBox(Dialog)
        self.units_groupBox.setCheckable(False)
        self.units_groupBox.setObjectName("units_groupBox")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.units_groupBox)
        self.horizontalLayout_9.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.SI_radioButton = QtGui.QRadioButton(self.units_groupBox)
        self.SI_radioButton.setEnabled(True)
        self.SI_radioButton.setChecked(True)
        self.SI_radioButton.setObjectName("SI_radioButton")
        self.horizontalLayout_9.addWidget(self.SI_radioButton)
        self.IM_radioButton = QtGui.QRadioButton(self.units_groupBox)
        self.IM_radioButton.setObjectName("IM_radioButton")
        self.horizontalLayout_9.addWidget(self.IM_radioButton)
        self.horizontalLayout_10.addWidget(self.units_groupBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_h = QtGui.QLabel(Dialog)
        self.label_h.setObjectName("label_h")
        self.horizontalLayout.addWidget(self.label_h)
        self.lineEdit_h = QtGui.QLineEdit(Dialog)
        self.lineEdit_h.setInputMask("")
        self.lineEdit_h.setMaxLength(32767)
        self.lineEdit_h.setCursorPosition(3)
        self.lineEdit_h.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_h.setObjectName("lineEdit_h")
        self.horizontalLayout.addWidget(self.lineEdit_h)
        self.unitlabel_h = QtGui.QLabel(Dialog)
        self.unitlabel_h.setObjectName("unitlabel_h")
        self.horizontalLayout.addWidget(self.unitlabel_h)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_deltaT = QtGui.QLabel(Dialog)
        self.label_deltaT.setObjectName("label_deltaT")
        self.horizontalLayout_2.addWidget(self.label_deltaT)
        self.lineEdit_deltaT = QtGui.QLineEdit(Dialog)
        self.lineEdit_deltaT.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_deltaT.setObjectName("lineEdit_deltaT")
        self.horizontalLayout_2.addWidget(self.lineEdit_deltaT)
        self.unitlabel_deltaT = QtGui.QLabel(Dialog)
        self.unitlabel_deltaT.setObjectName("unitlabel_deltaT")
        self.horizontalLayout_2.addWidget(self.unitlabel_deltaT)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_mu = QtGui.QLabel(Dialog)
        self.label_mu.setObjectName("label_mu")
        self.horizontalLayout_6.addWidget(self.label_mu)
        self.lineEdit_mu = QtGui.QLineEdit(Dialog)
        self.lineEdit_mu.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_mu.setObjectName("lineEdit_mu")
        self.horizontalLayout_6.addWidget(self.lineEdit_mu)
        self.unitlabel_mu = QtGui.QLabel(Dialog)
        self.unitlabel_mu.setObjectName("unitlabel_mu")
        self.horizontalLayout_6.addWidget(self.unitlabel_mu)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_Vson = QtGui.QLabel(Dialog)
        self.label_Vson.setObjectName("label_Vson")
        self.horizontalLayout_7.addWidget(self.label_Vson)
        self.lineEdit_Vson = QtGui.QLineEdit(Dialog)
        self.lineEdit_Vson.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Vson.setReadOnly(True)
        self.lineEdit_Vson.setObjectName("lineEdit_Vson")
        self.horizontalLayout_7.addWidget(self.lineEdit_Vson)
        self.unitlabel_Vson = QtGui.QLabel(Dialog)
        self.unitlabel_Vson.setObjectName("unitlabel_Vson")
        self.horizontalLayout_7.addWidget(self.unitlabel_Vson)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_p = QtGui.QLabel(Dialog)
        self.label_p.setObjectName("label_p")
        self.horizontalLayout_3.addWidget(self.label_p)
        self.lineEdit_p = QtGui.QLineEdit(Dialog)
        self.lineEdit_p.setMaxLength(32778)
        self.lineEdit_p.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_p.setObjectName("lineEdit_p")
        self.horizontalLayout_3.addWidget(self.lineEdit_p)
        self.unitlabel_p = QtGui.QLabel(Dialog)
        self.unitlabel_p.setObjectName("unitlabel_p")
        self.horizontalLayout_3.addWidget(self.unitlabel_p)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_t = QtGui.QLabel(Dialog)
        self.label_t.setObjectName("label_t")
        self.horizontalLayout_4.addWidget(self.label_t)
        self.lineEdit_t = QtGui.QLineEdit(Dialog)
        self.lineEdit_t.setInputMask("")
        self.lineEdit_t.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_t.setObjectName("lineEdit_t")
        self.horizontalLayout_4.addWidget(self.lineEdit_t)
        self.unitlabel_t = QtGui.QLabel(Dialog)
        self.unitlabel_t.setObjectName("unitlabel_t")
        self.horizontalLayout_4.addWidget(self.unitlabel_t)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_rho = QtGui.QLabel(Dialog)
        self.label_rho.setObjectName("label_rho")
        self.horizontalLayout_5.addWidget(self.label_rho)
        self.lineEdit_rho = QtGui.QLineEdit(Dialog)
        self.lineEdit_rho.setInputMask("")
        self.lineEdit_rho.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_rho.setObjectName("lineEdit_rho")
        self.horizontalLayout_5.addWidget(self.lineEdit_rho)
        self.unitlabel_rho = QtGui.QLabel(Dialog)
        self.unitlabel_rho.setObjectName("unitlabel_rho")
        self.horizontalLayout_5.addWidget(self.unitlabel_rho)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.acceptButton = QtGui.QPushButton(Dialog)
        self.acceptButton.setObjectName("acceptButton")
        self.verticalLayout_2.addWidget(self.acceptButton)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.titulo.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">Atmósfera Estandar (ISA)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.units_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Units", None, QtGui.QApplication.UnicodeUTF8))
        self.SI_radioButton.setText(QtGui.QApplication.translate("Dialog", "SI", None, QtGui.QApplication.UnicodeUTF8))
        self.IM_radioButton.setText(QtGui.QApplication.translate("Dialog", "IM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_h.setText(QtGui.QApplication.translate("Dialog", "Altura ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_h.setText(QtGui.QApplication.translate("Dialog", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_h.setPlaceholderText(QtGui.QApplication.translate("Dialog", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.unitlabel_h.setText(QtGui.QApplication.translate("Dialog", "[m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_deltaT.setText(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> T ISA</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_deltaT.setText(QtGui.QApplication.translate("Dialog", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_deltaT.setPlaceholderText(QtGui.QApplication.translate("Dialog", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.unitlabel_deltaT.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>[<span style=\" vertical-align:super;\">o</span>C]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mu.setText(QtGui.QApplication.translate("Dialog", "Viscosidad dinámica ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_mu.setText(QtGui.QApplication.translate("Dialog", "1.788e-5", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_mu.setPlaceholderText(QtGui.QApplication.translate("Dialog", "1.788e-5", None, QtGui.QApplication.UnicodeUTF8))
        self.unitlabel_mu.setText(QtGui.QApplication.translate("Dialog", "[m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Vson.setText(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Velocidad Sonido</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Vson.setText(QtGui.QApplication.translate("Dialog", "340.17", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Vson.setPlaceholderText(QtGui.QApplication.translate("Dialog", "340.17", None, QtGui.QApplication.UnicodeUTF8))
        self.unitlabel_Vson.setText(QtGui.QApplication.translate("Dialog", "`[m/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_p.setText(QtGui.QApplication.translate("Dialog", "Presión", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_p.setText(QtGui.QApplication.translate("Dialog", "101325.0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_p.setPlaceholderText(QtGui.QApplication.translate("Dialog", "101325.00", None, QtGui.QApplication.UnicodeUTF8))
        self.unitlabel_p.setText(QtGui.QApplication.translate("Dialog", "[Pa]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_t.setText(QtGui.QApplication.translate("Dialog", "Temperatura", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_t.setText(QtGui.QApplication.translate("Dialog", "288.00", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_t.setPlaceholderText(QtGui.QApplication.translate("Dialog", "288.00", None, QtGui.QApplication.UnicodeUTF8))
        self.unitlabel_t.setText(QtGui.QApplication.translate("Dialog", "[K]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rho.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Densidad</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_rho.setText(QtGui.QApplication.translate("Dialog", "1.2258", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_rho.setPlaceholderText(QtGui.QApplication.translate("Dialog", "1.2258", None, QtGui.QApplication.UnicodeUTF8))
        self.unitlabel_rho.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>[Kg/ m<span style=\" vertical-align:super;\">3</span>]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.acceptButton.setText(QtGui.QApplication.translate("Dialog", "Aceptar", None, QtGui.QApplication.UnicodeUTF8))

